@startuml

title __PLAYERACTIONS's Class Diagram__\n

  namespace model {
    namespace actors.actions {
      namespace playerActions {
        class model.actors.actions.playerActions.FarmerActions {
            + FarmerActions()
            + add_animal()
            + feed_all_animals()
            + feed_animal()
            + fertilize()
            + fertilize_all()
            + get_all_resources()
            + get_resources()
            + give_water()
            + give_water_all()
            + harvest()
            + harvest_all()
            + move_item()
            + plant()
            + plant_all()
            + plow()
            + plow_all()
            + remove_animal()
            + water()
            + water_all()
        }
      }
    }
  }
  

  namespace model {
    namespace actors.actions {
      namespace playerActions {
        class model.actors.actions.playerActions.LandlordActions {
            + LandlordActions()
            + buy_item()
            + sell_item()
        }
      }
    }
  }
  

  namespace model {
    namespace actors.actions {
      namespace playerActions {
        abstract class model.actors.actions.playerActions.PlayerActions {
            # argument : ActionArguments<Place, ?, GameMap>
            - roleClass : HashMap<Role, Class<? extends Person>>
            + PlayerActions()
            + enter()
            + executeAction()
            + leave()
            # damageTool()
            # doAll()
            - getMethodByName()
        }
      }
    }
  }
  

  model.actors.actions.playerActions.PlayerActions o-- T : person


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
