@startuml

title __PLANTS's Class Diagram__\n

  namespace model {
    namespace item {
      namespace plants {
        class model.item.plants.GamePlant {
            + GamePlant()
        }
      }
    }
  }
  

  namespace model {
    namespace item {
      namespace plants {
        abstract class model.item.plants.Plant {
            # calendar : Calendar
            - chunk : PlantChunk
            - daysToHarvest : int
            - daysToHarvestInitial : int
            - daysWithoutWater : int
            - growthRate : int
            - maxGrowthLevel : int
            - random : Random
            + getDaysToHarvest()
            + getGrowthLevel()
            + getLifeStage()
            + getPlantType()
            + getProduct()
            + grow()
            + planted()
            # Plant()
            - checklifeStage()
            - turnToProduct()
        }
      }
    }
  }
  

  namespace model {
    namespace item {
      namespace plants {
        enum PlantLife {
          ADULT_PLANT
          DEAD
          HARVESTABLE
          PRODUCT
          SEED
          SMALL_PLANT
          SPROUT
          name
        }
      }
    }
  }
  

  namespace model {
    namespace item {
      namespace plants {
        class model.item.plants.PlantFactory {
            + createCarrot()
            + createOnion()
            + createPotato()
            + createWeat()
        }
      }
    }
  }
  

  namespace model {
    namespace item {
      namespace plants {
        interface model.item.plants.PlantInterface {
            {abstract} + getDaysToHarvest()
            {abstract} + getGrowthLevel()
            {abstract} + getLifeStage()
            {abstract} + getPlantType()
            {abstract} + getProduct()
            {abstract} + grow()
            {abstract} + planted()
        }
      }
    }
  }
  

  model.item.plants.Plant .up.|> PlantInterface
  model.item.plants.Plant o-- model.item.plants.Plant.PlantLife : lifeStage
  model.item.plants.Plant +-down- model.item.plants.Plant.PlantLife
  model.item.plants.PlantFactory .up.|> Serializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
