@startuml

title __ACTIONS's Class Diagram__\n

  namespace model {
    namespace actors.actions {
      interface model.actors.actions.Actions {
          {abstract} + getActions()
          {abstract} + updateActions()
      }
    }
  }
  

  namespace model {
    namespace actors.actions {
      abstract class model.actors.actions.ActionsManager {
          # availableActions : Set<Action>
          + getActions()
          + resetActions()
          + updateActions()
          # ActionsManager()
      }
    }
  }
  

  namespace model {
    namespace actors.actions {
      enum Action {
        ADD_ANIMAL
        BUY_ITEM
        FEED_ALL_ANIMALS
        FEED_ANIMAL
        FERTILIZE
        FERTILIZE_ALL
        GET_ALL_RESOURCES
        GET_RESOURCES
        GIVE_WATER
        GIVE_WATER_ALL
        HARVEST
        HARVEST_ALL
        MOVE_ITEM
        PLANT
        PLANT_ALL
        PLOW
        PLOW_ALL
        REMOVE_ANIMAL
        SELL_ITEM
        WATER
        WATER_ALL
        itemValidator
        name
        optional
      }
    }
  }
  

  namespace model {
    namespace actors.actions {
      interface model.actors.actions.ActionsManager.DualItemValidator {
      }
    }
  }
  

  namespace model {
    namespace actors.actions {
      interface model.actors.actions.ActionsManager.ItemTypeValidator {
          {abstract} + validateItemType()
      }
    }
  }
  

  namespace model {
    namespace actors.actions {
      interface model.actors.actions.ActionsManager.LandAbstractValidator {
          {abstract} + validateLandAbstract()
      }
    }
  }
  

  namespace model {
    namespace actors.actions {
      class model.actors.actions.PlaceActions {
          # place : Place
          + PlaceActions()
      }
    }
  }
  

  namespace model {
    namespace actors.actions {
      class model.actors.actions.PlayerActions {
          - accessiblePlaces : HashSet<Places>
          - person : Person
          + PlayerActions()
          + PlayerActions()
          + add_animal()
          + buy_item()
          + enter()
          + executeAction()
          + feed_all_animals()
          + feed_animal()
          + fertilize()
          + fertilize_all()
          + get_all_resources()
          + get_resources()
          + give_water()
          + give_water_all()
          + harvest()
          + harvest_all()
          + leave()
          + move_item()
          + plant()
          + plant_all()
          + plow()
          + plow_all()
          + remove_animal()
          + sell_item()
          + water()
          + water_all()
          - damageTool()
          - doAll()
          - getMethodByName()
      }
    }
  }
  

  model.actors.actions.ActionsManager .up.|> Actions
  model.actors.actions.ActionsManager +-down- model.actors.actions.ActionsManager.Action
  model.actors.actions.ActionsManager +-down- model.actors.actions.ActionsManager.DualItemValidator
  model.actors.actions.ActionsManager +-down- model.actors.actions.ActionsManager.ItemTypeValidator
  model.actors.actions.ActionsManager +-down- model.actors.actions.ActionsManager.LandAbstractValidator
  model.actors.actions.ActionsManager.Action o-- model.actors.actions.ActionsManager.DualItemValidator : itemValidator


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
