@startuml

title __CHUNKS's Class Diagram__\n

  namespace model {
    namespace place {
      namespace land {
        namespace chunks {
          class model.place.land.chunks.AnimalChunk {
              - animal : AnimalAbstract
              - land : AnimalLand
              + AnimalChunk()
              + getAnimal()
              + getLand()
              + removeAnimal()
              + resetActions()
              + setAnimal()
              + update()
          }
        }
      }
    }
  }
  

  namespace model {
    namespace place {
      namespace land {
        namespace chunks {
          abstract class model.place.land.chunks.Chunk {
              + getActions()
              + resetActions()
              + update()
          }
        }
      }
    }
  }
  

  namespace model {
    namespace place {
      namespace land {
        namespace chunks {
          class model.place.land.chunks.PlantChunk {
              - fertilizationLevel : float
              - isPlowed : boolean
              - land : PlantLand
              - plant : Plant
              - random : Random
              - waterLevel : float
              + PlantChunk()
              + getDirtStatus()
              + getFertilizationLevel()
              + getLand()
              + getPlant()
              + getWaterLevel()
              + increaseFertilizationLevel()
              + increaseWaterLevel()
              + isPlowed()
              + resetActions()
              + setDirtStatus()
              + setPlant()
              + update()
          }
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
