@startuml

title __MODEL's Class Diagram__\n

  namespace model {
    class model.Constants {
        {static} + BARN_INVENTORY_MAX : int
        {static} + BASE_LAND_PRICE : int
        {static} + CARROT_PRICE : int
        {static} + CHICKEN_PRICE : int
        {static} + CHUNK_FERTILIZATION_DEACRESE : int
        {static} + CHUNK_WATER_DEACRESE : int
        {static} + COW_PRICE : int
        {static} + EGGS_PRICE : int
        {static} + FEED_INDEX : int
        {static} + FEED_MAX : int
        {static} + FERTILIZATION_INDEX : int
        {static} + FERTILIZATION_MAX : int
        {static} + FERTILIZER_PRICE : int
        {static} + GIVE_WATER_INDEX : int
        {static} + GIVE_WATER_MAX : int
        {static} + GOAT_PRICE : int
        {static} + GROWTH_RATE : int
        {static} + HARVEST_MULTIPLIER : int
        {static} + HIGH_PRODUCTIVITY : int
        {static} + HUNGER_INCREASE : int
        {static} + INVENTORY_MAX : int
        {static} + IRON_FERTILIZER_PRICE : int
        {static} + IRON_HOE_PRICE : int
        {static} + IRON_MODIFIER : int
        {static} + IRON_SCISSORS_PRICE : int
        {static} + IRON_SICKLE_PRICE : int
        {static} + IRON_WATERINGCAN_PRICE : int
        {static} + LAND_SELL_PRICE : int
        {static} + LOW_PRODUCTIVITY : int
        {static} + MARKET_SHOP_MAX : int
        {static} + MAX_GROWTH : int
        {static} + MEAT_PRICE : int
        {static} + MEDIUM_PRODUCTIVITY : int
        {static} + MILK_PRICE : int
        {static} + NEGATIVE_PRODUCTIVITY : int
        {static} + ONION_PRICE : int
        {static} + PIG_PRICE : int
        {static} + PLANT_DAYS_WITHOUT_WATER : int
        {static} + PLANT_FERTILIZATION_DEACRESE : int
        {static} + PLANT_WATER_DEACRESE : int
        {static} + POTATO_PRICE : int
        {static} + STACK_MAX : int
        {static} + THIRST_INCREASE : int
        {static} + WATERING_INDEX : int
        {static} + WATERING_MAX : int
        {static} + WHEAT_PRICE : int
        {static} + WOOD_FERTILIZER_PRICE : int
        {static} + WOOD_HOE_PRICE : int
        {static} + WOOD_MODIFIER : int
        {static} + WOOD_SCISSORS_PRICE : int
        {static} + WOOD_SICKLE_PRICE : int
        {static} + WOOD_WATERINGCAN_PRICE : int
        {static} + WOOL_PRICE : int
    }
  }
  

  namespace model {
    class model.Model {
        - backup : GameBackupManager
        - calendar : Calendar
        - farmer : Farmer
        - landlord : Landlord
        - map : GameMap
        - oldInventory : Inventory
        - oldPlace : Place
        - selectedActor : Person
        - selectedItem : Object
        + Model()
        + getBackup()
        + getBarn()
        + getLands()
        + getMap()
        + getOldInventory()
        + getOldPlace()
        + getPersonPlace()
        + getRoles()
        + getSelectedItem()
        + getSelectedPerson()
        + initializeGameBackup()
        + sendAction()
        + setOldInventory()
        + setOldPlace()
        + setSelectedItem()
        + setSelectedPerson()
        + update()
    }
  }
  

  model.Model .up.|> Serializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
