@startuml

title __PERSON's Class Diagram__\n

  namespace model {
    namespace actors.person {
      class model.actors.person.Farmer {
          - creator : ItemCreator
          - inventory : Inventory
          + Farmer()
          + getInventory()
          + toString()
      }
    }
  }
  

  namespace model {
    namespace actors.person {
      class model.actors.person.Landlord {
          - balance : int
          + Landlord()
          + getBalance()
          + setBalance()
          + toString()
      }
    }
  }
  

  namespace model {
    namespace actors.person {
      interface model.actors.person.Person {
          {abstract} + getAccessiblePlaces()
          {abstract} + getActions()
          {abstract} + getPlace()
          {abstract} + getRole()
          {abstract} + setPlace()
      }
    }
  }
  

  namespace model {
    namespace actors.person {
      abstract class model.actors.person.PersonAbstract {
          # accessiblePlaces : HashSet<Places>
          # personAction : PlayerActions<? extends Person>
          # place : Place
          + getAccessiblePlaces()
          + getActions()
          + getPlace()
          + getRole()
          + setPlace()
      }
    }
  }
  

  namespace model {
    namespace actors.person {
      enum Role {
        FARMER
        LANDLORD
        name
      }
    }
  }
  

  model.actors.person.PersonAbstract .up.|> Person
  model.actors.person.PersonAbstract o-- model.actors.person.PersonAbstract.Role : role
  model.actors.person.PersonAbstract +-down- model.actors.person.PersonAbstract.Role


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
