@startuml

title __EXCEPTIONS's Class Diagram__\n

  namespace model {
    namespace exceptions {
      class model.exceptions.CustomExceptions {
      }
    }
  }
  

  namespace model {
    namespace exceptions {
      class model.exceptions.CustomExceptions.ActionNotAvailableException {
          + ActionNotAvailableException()
          + toString()
      }
    }
  }
  

  namespace model {
    namespace exceptions {
      class model.exceptions.CustomExceptions.CannotBuyItemException {
          + CannotBuyItemException()
      }
    }
  }
  

  namespace model {
    namespace exceptions {
      class model.exceptions.CustomExceptions.CannotSellItemException {
          + CannotSellItemException()
      }
    }
  }
  

  namespace model {
    namespace exceptions {
      class model.exceptions.CustomExceptions.InventoryIsFullException {
          + InventoryIsFullException()
      }
    }
  }
  

  namespace model {
    namespace exceptions {
      class model.exceptions.CustomExceptions.LandIsAlreadyPlowedException {
          + LandIsAlreadyPlowedException()
          + toString()
      }
    }
  }
  

  namespace model {
    namespace exceptions {
      class model.exceptions.CustomExceptions.LandIsNotPlowedException {
          + LandIsNotPlowedException()
          + toString()
      }
    }
  }
  

  namespace model {
    namespace exceptions {
      class model.exceptions.CustomExceptions.MaxFertilizationLevelReachedException {
          + MaxFertilizationLevelReachedException()
      }
    }
  }
  

  namespace model {
    namespace exceptions {
      class model.exceptions.CustomExceptions.MaxWaterLevelReachedException {
          + MaxWaterLevelReachedException()
      }
    }
  }
  

  namespace model {
    namespace exceptions {
      class model.exceptions.CustomExceptions.MinimumHungerException {
          + MinimumHungerException()
      }
    }
  }
  

  namespace model {
    namespace exceptions {
      class model.exceptions.CustomExceptions.NoAnimalFoundException {
          + NoAnimalFoundException()
      }
    }
  }
  

  namespace model {
    namespace exceptions {
      class model.exceptions.CustomExceptions.NoEnoughMoneyException {
          + NoEnoughMoneyException()
      }
    }
  }
  

  namespace model {
    namespace exceptions {
      class model.exceptions.CustomExceptions.NoFoodFoundException {
          + NoFoodFoundException()
      }
    }
  }
  

  namespace model {
    namespace exceptions {
      class model.exceptions.CustomExceptions.NoItemFoundException {
          + NoItemFoundException()
      }
    }
  }
  

  namespace model {
    namespace exceptions {
      class model.exceptions.CustomExceptions.NoProductFoundException {
          + NoProductFoundException()
      }
    }
  }
  

  namespace model {
    namespace exceptions {
      class model.exceptions.CustomExceptions.NoSeedFoundException {
          + NoSeedFoundException()
          + toString()
      }
    }
  }
  

  namespace model {
    namespace exceptions {
      class model.exceptions.CustomExceptions.NoSellableLandException {
          + NoSellableLandException()
      }
    }
  }
  

  namespace model {
    namespace exceptions {
      class model.exceptions.CustomExceptions.NoToolFoundException {
          + NoToolFoundException()
      }
    }
  }
  

  namespace model {
    namespace exceptions {
      class model.exceptions.CustomExceptions.NotEnoughItemsException {
          + NotEnoughItemsException()
      }
    }
  }
  

  namespace model {
    namespace exceptions {
      class model.exceptions.CustomExceptions.PlaceNotAvailableException {
          + PlaceNotAvailableException()
          + toString()
      }
    }
  }
  

  namespace model {
    namespace exceptions {
      class model.exceptions.CustomExceptions.PlantIsNotHarvestableException {
          + PlantIsNotHarvestableException()
          + toString()
      }
    }
  }
  

  namespace model {
    namespace exceptions {
      class model.exceptions.CustomExceptions.SaveIsCorruptedException {
          + SaveIsCorruptedException()
          + toString()
      }
    }
  }
  

  model.exceptions.CustomExceptions +-down- model.exceptions.CustomExceptions.ActionNotAvailableException
  model.exceptions.CustomExceptions +-down- model.exceptions.CustomExceptions.CannotBuyItemException
  model.exceptions.CustomExceptions +-down- model.exceptions.CustomExceptions.CannotSellItemException
  model.exceptions.CustomExceptions +-down- model.exceptions.CustomExceptions.InventoryIsFullException
  model.exceptions.CustomExceptions +-down- model.exceptions.CustomExceptions.LandIsAlreadyPlowedException
  model.exceptions.CustomExceptions +-down- model.exceptions.CustomExceptions.LandIsNotPlowedException
  model.exceptions.CustomExceptions +-down- model.exceptions.CustomExceptions.MaxFertilizationLevelReachedException
  model.exceptions.CustomExceptions +-down- model.exceptions.CustomExceptions.MaxWaterLevelReachedException
  model.exceptions.CustomExceptions +-down- model.exceptions.CustomExceptions.MinimumHungerException
  model.exceptions.CustomExceptions +-down- model.exceptions.CustomExceptions.NoAnimalFoundException
  model.exceptions.CustomExceptions +-down- model.exceptions.CustomExceptions.NoEnoughMoneyException
  model.exceptions.CustomExceptions +-down- model.exceptions.CustomExceptions.NoFoodFoundException
  model.exceptions.CustomExceptions +-down- model.exceptions.CustomExceptions.NoItemFoundException
  model.exceptions.CustomExceptions +-down- model.exceptions.CustomExceptions.NoProductFoundException
  model.exceptions.CustomExceptions +-down- model.exceptions.CustomExceptions.NoSeedFoundException
  model.exceptions.CustomExceptions +-down- model.exceptions.CustomExceptions.NoSellableLandException
  model.exceptions.CustomExceptions +-down- model.exceptions.CustomExceptions.NoToolFoundException
  model.exceptions.CustomExceptions +-down- model.exceptions.CustomExceptions.NotEnoughItemsException
  model.exceptions.CustomExceptions +-down- model.exceptions.CustomExceptions.PlaceNotAvailableException
  model.exceptions.CustomExceptions +-down- model.exceptions.CustomExceptions.PlantIsNotHarvestableException
  model.exceptions.CustomExceptions +-down- model.exceptions.CustomExceptions.SaveIsCorruptedException


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
