@startuml

title __ITEM's Class Diagram__\n

  namespace model {
    namespace item {
      abstract class model.item.Item {
          # maxNumber : int
          # number : int
          # price : int
          # status : double
          # type : ItemType
          + Item()
          + clone()
          + compareTo()
          + getMaxNumber()
          + getNumber()
          + getPrice()
          + getStatus()
          + getType()
          + setNumber()
      }
    }
  }
  

  namespace model {
    namespace item {
      class model.item.ItemCreator {
          - MAX_INVENTORY_SIZE : int
          - animalFactory : AnimalFactory
          - inventory : ArrayList<Item>
          - ironFactory : IronFactory
          - plantFactory : PlantFactory
          - random : Random
          - randomMethods : Item[]
          - woodFactory : WoodFactory
          + ItemCreator()
          + getRandomItem()
          + getWoodSet()
          - createStandardInventory()
      }
    }
  }
  

  namespace model {
    namespace item {
      interface model.item.ItemInterface {
          {abstract} + clone()
          {abstract} + getMaxNumber()
          {abstract} + getNumber()
          {abstract} + getPrice()
          {abstract} + getStatus()
          {abstract} + getType()
          {abstract} + setNumber()
      }
    }
  }
  

  namespace model {
    namespace item {
      interface model.item.ItemType {
      }
    }
  }
  

  namespace model {
    namespace item {
      enum Animals {
        CHICKEN
        COW
        GOAT
        PIG
        name
      }
    }
  }
  

  namespace model {
    namespace item {
      enum Plants {
        CARROT
        ONION
        POTATO
        WHEAT
        name
      }
    }
  }
  

  namespace model {
    namespace item {
      enum Tools {
        FERTILIZER
        HOE
        SCISSORS
        SICKLE
        WATERINGCAN
        name
      }
    }
  }
  

  namespace model {
    namespace item {
      enum Material {
        IRON
        WOOD
        modifier
        name
      }
    }
  }
  

  namespace model {
    namespace item {
      enum productsType {
        EGGS
        MEAT
        MILK
        WOOL
        name
      }
    }
  }
  

  model.item.Item .up.|> Cloneable
  model.item.Item .up.|> Comparable
  model.item.Item .up.|> ItemInterface
  model.item.Item .up.|> Serializable
  model.item.ItemCreator .up.|> Serializable
  model.item.ItemType +-down- model.item.ItemType.Animals
  model.item.ItemType +-down- model.item.ItemType.Plants
  model.item.ItemType +-down- model.item.ItemType.Tools
  model.item.ItemType +-down- model.item.ItemType.productsType
  model.item.ItemType.Animals .up.|> model.item.ItemType
  model.item.ItemType.Plants .up.|> model.item.ItemType
  model.item.ItemType.Tools .up.|> model.item.ItemType
  model.item.ItemType.Tools +-down- model.item.ItemType.Tools.Material
  model.item.ItemType.productsType .up.|> model.item.ItemType


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
